import type { Metadata } from "next";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeflex/primeflex.css";

import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import client from '../lib/apolloClient';
import { ApolloProvider } from "@apollo/client";
import { ApolloWrapper } from "@/lib/apolloWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <PrimeReactProvider>
        <html lang="en">
          <head>
            <script src="https://unpkg.com/@rdkit/rdkit/dist/RDKit_minimal.js"></script>
          </head>
          <body>
            <ApolloWrapper>
              {children}
            </ApolloWrapper>
          </body>
        </html>
      </PrimeReactProvider>

  );
}
